Start-Process python -ArgumentList preprocessing.py,10
Start-Process python -ArgumentList preprocessing.py,20
Start-Process python -ArgumentList preprocessing.py,30
Start-Process python -ArgumentList preprocessing.py,40
Start-Process python -ArgumentList preprocessing.py,50
Start-Process python -ArgumentList preprocessing.py,60
Start-Process python -ArgumentList preprocessing.py,70
Start-Process python -ArgumentList preprocessing.py,80
Start-Process python -ArgumentList preprocessing.py,90
Start-Process python -ArgumentList preprocessing.py,100
Start-Process python -ArgumentList preprocessing.py,125
Start-Process python -ArgumentList preprocessing.py,150
Start-Process python -ArgumentList preprocessing.py,175
Start-Process python -ArgumentList preprocessing.py,200
Start-Process python -ArgumentList preprocessing.py,300
